version: "3.9"

services:
  users_alembic:
    image: users_alembic:latest
    build:
      context: ${PWD}/users
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run migrations' && \
      alembic stamp head --purge && \
      alembic revision --autogenerate -m "Migrations" && \
      alembic upgrade head"
    volumes:
      - ${PWD}/users/:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      users_database:
        condition: service_healthy
    networks:
      - raindinners_network
