version: "3.9"

services:
  auth:
    image: auth:latest
    build:
      context: ${PWD}/auth
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Running Auth Backend' && \
      python main.py"
    volumes:
      - ${PWD}/auth/app:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      auth_database:
        condition: service_healthy
    expose:
      - ${AUTH_PORT}
    networks:
      - raindinners_network
    restart: always
