version: "3.9"

services:
  users:
    image: users:latest
    build:
      context: ${PWD}/users
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Running Auth Backend' && \
      python main.py"
    volumes:
      - ${PWD}/users/app:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      users_database:
        condition: service_healthy
    expose:
      - ${AUTH_PORT}
    networks:
      - raindinners_network
    restart: always
