version: "3.9"

services:
  users_database:
    image: postgres:15-bookworm
    restart: always
    volumes:
      - postgres_users_data_database:/var/lib/postgresql/data/
    env_file:
      - ${PWD}/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - ${DATABASE_PORT}
    networks:
      - raindinners_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_users_data_database:
