version: "3.9"

services:
  users_tests:
    image: users_tests:latest
    build:
      context: ${PWD}/users
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run tests' && \
      python -m pytest --capture=sys --cov=app --cov-report html tests"
    volumes:
      - ${PWD}/users/:/app
    env_file:
      - ${PWD}/.env
    environment:
      DATABASE_HOSTNAME: users_tests_database
    depends_on:
      users_tests_database:
        condition: service_healthy
    networks:
      - raindinners_network
