version: "3.9"

services:
  auth_tests_database:
    image: postgres:latest
    env_file:
      - ${PWD}/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - ${DATABASE_PORT}
    networks:
      - raindinners_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
